# Generated by Django 5.0.6 on 2024-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='datasource',
        ),
    ]
