# Generated by Django 5.0.6 on 2024-06-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0008_bot_bot_instance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_instance_id',
        ),
        migrations.CreateModel(
            name='BotInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_src.bot')),
            ],
        ),
    ]
