# Generated by Django 5.0.6 on 2024-06-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0009_remove_bot_bot_instance_id_botinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='datasources',
            field=models.ManyToManyField(related_name='datasources', to='bot_src.datasource'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_src.telegramgroup'),
        ),
    ]
