# Generated by Django 5.0.6 on 2024-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0010_remove_collection_group_remove_datasource_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
