# Generated by Django 5.0.6 on 2024-06-22 21:01

import bot_src.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0011_alter_datasource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(upload_to=bot_src.models.get_upload_path),
        ),
    ]
