# Generated by Django 5.0.6 on 2024-07-17 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0012_alter_datasource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
