# Generated by Django 5.0.6 on 2024-07-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0013_alter_datasource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_data', to='bot_src.collection'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
