# Generated by Django 5.0.6 on 2024-07-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_src', '0014_datasource_collection_alter_datasource_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='datasources',
        ),
    ]
